version: "3.8"
services:
  node:
    image: node:14.17.3-alpine3.14
    volumes:
      - ./projects/backend:/projects/backend
      - ./projects/frontend:/projects/frontend
    ports:
      - "3000:3000"
      - "8000:8000"
    entrypoint: sh
    command:
      - -c
      - |
        tail -f /dev/null
    networks:
      - dev
  mongodb:
    image: mongo:4.4-focal
    volumes:
      - ./data:/data/db
      - ./docker/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: app
    ports:
      - "27017:27017"
    networks:
      - dev

networks:
  dev:
    driver: "bridge"
